version: "3"
services:
    bryntum_pdfexport_server:
        build: .
        image: bryntum_pdfexport_server
        container_name: bryntum_pdfexport_server
        ports:
            - "8080:8080"
            - "8081:8081"
